name: Deploy static files into GitHub Pages
on:
  workflow_dispatch:

jobs:
  aws-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitHub Repository
        uses: actions/checkout@v4

      - name: Copy website files to Nginx
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/tmp/website"

      - name: Deploy into website
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying website..."

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy the Website
        uses: actions/deploy-pages@v4
